#!/usr/bin/env python3
"""Generate real text embeddings for the scholarly-search example.

Reads ``corpus.json`` (papers + authors + citations + daily citation counts +
query strings), embeds every paper abstract and every query string with a local
Ollama ``nomic-embed-text-v2-moe`` model (768-dim), and writes two runnable,
self-contained CQL files with the real vectors baked in:

  * ``../data.cql``     -- INSERTs for every table, paper rows carry embeddings
  * ``../queries.cql``  -- the demo queries, ANN clauses filled with query vectors

No API key and no network service is needed at query time: the committed
``data.cql``/``queries.cql`` are plain CQL. Re-run this script (against any
Ollama serving the model) only when you change the corpus.

  ollama pull nomic-embed-text-v2-moe          # one-time
  python3 gen_embeddings.py                     # regenerate ../data.cql, ../queries.cql

Override the endpoint/model with OLLAMA_URL / OLLAMA_MODEL env vars.
"""

import json
import os
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434/api/embed")
MODEL = os.environ.get("OLLAMA_MODEL", "nomic-embed-text-v2-moe")
DIM = 768  # nomic-embed-text-v2-moe output dimension


def embed(text: str) -> list[float]:
    """Return the embedding vector for ``text`` (fail loud on any problem)."""
    body = json.dumps({"model": MODEL, "input": text}).encode()
    req = urllib.request.Request(
        OLLAMA_URL, data=body, headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.load(resp)
    except Exception as e:  # noqa: BLE001 - surface the real cause
        sys.exit(
            f"embedding request to {OLLAMA_URL} (model {MODEL}) failed: {e}\n"
            f"Is Ollama running and the model pulled? `ollama pull {MODEL}`"
        )
    vec = data.get("embeddings", [data.get("embedding")])[0]
    if vec is None or len(vec) != DIM:
        sys.exit(f"expected {DIM}-dim embedding, got {None if vec is None else len(vec)}")
    return vec


def vec_literal(vec: list[float]) -> str:
    """CQL vector literal, e.g. ``[0.0288, -0.0016, ...]`` (6 dp keeps it compact)."""
    return "[" + ", ".join(f"{x:.6f}" for x in vec) + "]"


def cql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    corpus = json.loads((HERE / "corpus.json").read_text())
    out = []
    out.append("-- GENERATED by embeddings/gen_embeddings.py -- do not edit by hand.")
    out.append(f"-- Embeddings: {MODEL} ({DIM}-dim), from each paper abstract.")
    out.append("USE scholar;\n")

    # Authors (phonetic-searchable names; graph vertices).
    for a in corpus["authors"]:
        out.append(
            f"INSERT INTO author (author_id, name, affiliation) VALUES "
            f"({a['id']}, {cql_str(a['name'])}, {cql_str(a.get('affiliation', ''))});"
        )
    out.append("")

    # Papers: full-text (title/abstract), real embedding vector, graph vertices.
    for p in corpus["papers"]:
        vec = embed(p["abstract"])
        print(f"  embedded paper {p['id']}: {p['title'][:48]}", file=sys.stderr)
        out.append(
            f"INSERT INTO paper (paper_id, title, abstract, year, venue, embedding) VALUES "
            f"({p['id']}, {cql_str(p['title'])}, {cql_str(p['abstract'])}, "
            f"{p['year']}, {cql_str(p['venue'])}, {vec_literal(vec)});"
        )
    out.append("")

    # Authorship edges (graph) + a denormalized author_name for phonetic demo.
    for (paper_id, author_id, pos) in corpus["authored"]:
        out.append(
            f"INSERT INTO authored (author_id, paper_id, author_position) VALUES "
            f"({author_id}, {paper_id}, {pos});"
        )
    out.append("")

    # Citation edges (graph).
    for (src, dst) in corpus["cites"]:
        out.append(f"INSERT INTO cites (citing_paper_id, cited_paper_id) VALUES ({src}, {dst});")
    out.append("")

    # Daily citation counts -> RRD consolidation source (trend signal).
    for c in corpus["daily_counts"]:
        out.append(
            f"INSERT INTO paper_citations_daily (paper_id, day, citations) VALUES "
            f"({c['paper_id']}, {cql_str(c['day'])}, {c['count']});"
        )
    out.append("")
    (HERE.parent / "data.cql").write_text("\n".join(out) + "\n")
    print(f"wrote {HERE.parent / 'data.cql'} ({len(corpus['papers'])} papers)", file=sys.stderr)

    # Fill query vectors into queries.template.cql -> queries.cql.
    template = (HERE / "queries.template.cql").read_text()
    for q in corpus["queries"]:
        qvec = embed(q["text"])
        print(f"  embedded query {q['name']}: {q['text'][:48]}", file=sys.stderr)
        template = template.replace(f"@@Q:{q['name']}@@", vec_literal(qvec))
    if "@@Q:" in template:
        sys.exit("unfilled @@Q:...@@ placeholder remains in queries.template.cql")
    (HERE.parent / "queries.cql").write_text(template)
    print(f"wrote {HERE.parent / 'queries.cql'}", file=sys.stderr)


if __name__ == "__main__":
    main()
