// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type CqlValue = ferrosa::udf::types::CqlValue;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_invoke_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let base41 = arg0;
    let len41 = arg1;
    let mut result41 = _rt::Vec::with_capacity(len41);
    for i in 0..len41 {
        let base = base41.add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
        let e41 = {
            let l0 = i32::from(*base.add(0).cast::<u8>());
            use ferrosa::udf::types::CqlValue as V40;
            let v40 = match l0 {
                0 => V40::Null,
                1 => {
                    let e40 = {
                        let l1 = *base.add(8).cast::<i32>();
                        l1
                    };
                    V40::IntVal(e40)
                }
                2 => {
                    let e40 = {
                        let l2 = *base.add(8).cast::<i64>();
                        l2
                    };
                    V40::BigintVal(e40)
                }
                3 => {
                    let e40 = {
                        let l3 = *base.add(8).cast::<f32>();
                        l3
                    };
                    V40::FloatVal(e40)
                }
                4 => {
                    let e40 = {
                        let l4 = *base.add(8).cast::<f64>();
                        l4
                    };
                    V40::DoubleVal(e40)
                }
                5 => {
                    let e40 = {
                        let l5 = i32::from(*base.add(8).cast::<u8>());
                        _rt::bool_lift(l5 as u8)
                    };
                    V40::BooleanVal(e40)
                }
                6 => {
                    let e40 = {
                        let l6 = *base.add(8).cast::<*mut u8>();
                        let l7 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len8 = l7;
                        let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                        _rt::string_lift(bytes8)
                    };
                    V40::TextVal(e40)
                }
                7 => {
                    let e40 = {
                        let l9 = *base.add(8).cast::<*mut u8>();
                        let l10 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len11 = l10;
                        _rt::Vec::from_raw_parts(l9.cast(), len11, len11)
                    };
                    V40::BlobVal(e40)
                }
                8 => {
                    let e40 = {
                        let l12 = *base.add(8).cast::<*mut u8>();
                        let l13 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len14 = l13;
                        let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);
                        _rt::string_lift(bytes14)
                    };
                    V40::UuidVal(e40)
                }
                9 => {
                    let e40 = {
                        let l15 = *base.add(8).cast::<i64>();
                        l15
                    };
                    V40::TimestampVal(e40)
                }
                10 => {
                    let e40 = {
                        let l16 = *base.add(8).cast::<i32>();
                        l16
                    };
                    V40::DateVal(e40)
                }
                11 => {
                    let e40 = {
                        let l17 = *base.add(8).cast::<i64>();
                        l17
                    };
                    V40::TimeVal(e40)
                }
                12 => {
                    let e40 = {
                        let l18 = i32::from(*base.add(8).cast::<i16>());
                        l18 as i16
                    };
                    V40::SmallintVal(e40)
                }
                13 => {
                    let e40 = {
                        let l19 = i32::from(*base.add(8).cast::<i8>());
                        l19 as i8
                    };
                    V40::TinyintVal(e40)
                }
                14 => {
                    let e40 = {
                        let l20 = *base.add(8).cast::<*mut u8>();
                        let l21 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len22 = l21;
                        let bytes22 = _rt::Vec::from_raw_parts(l20.cast(), len22, len22);
                        _rt::string_lift(bytes22)
                    };
                    V40::InetVal(e40)
                }
                15 => {
                    let e40 = {
                        let l23 = *base.add(8).cast::<*mut u8>();
                        let l24 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len25 = l24;
                        let l26 = *base
                            .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                            .cast::<i32>();
                        (_rt::Vec::from_raw_parts(l23.cast(), len25, len25), l26)
                    };
                    V40::DecimalVal(e40)
                }
                16 => {
                    let e40 = {
                        let l27 = *base.add(8).cast::<*mut u8>();
                        let l28 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len29 = l28;
                        _rt::Vec::from_raw_parts(l27.cast(), len29, len29)
                    };
                    V40::VarintVal(e40)
                }
                17 => {
                    let e40 = {
                        let l30 = *base.add(8).cast::<i32>();
                        let l31 = *base.add(12).cast::<i32>();
                        let l32 = *base.add(16).cast::<i64>();
                        (l30, l31, l32)
                    };
                    V40::DurationVal(e40)
                }
                18 => {
                    let e40 = {
                        let l33 = *base.add(8).cast::<*mut u8>();
                        let l34 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len35 = l34;
                        let bytes35 = _rt::Vec::from_raw_parts(l33.cast(), len35, len35);
                        _rt::string_lift(bytes35)
                    };
                    V40::AsciiVal(e40)
                }
                19 => {
                    let e40 = {
                        let l36 = *base.add(8).cast::<*mut u8>();
                        let l37 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len38 = l37;
                        let bytes38 = _rt::Vec::from_raw_parts(l36.cast(), len38, len38);
                        _rt::string_lift(bytes38)
                    };
                    V40::TimeuuidVal(e40)
                }
                20 => {
                    let e40 = {
                        let l39 = *base.add(8).cast::<i64>();
                        l39
                    };
                    V40::CounterVal(e40)
                }
                n => {
                    debug_assert_eq!(n, 21, "invalid enum discriminant");
                    V40::Unsupported
                }
            };
            v40
        };
        result41.push(e41);
    }
    _rt::cabi_dealloc(base41, len41 * (16 + 2 * ::core::mem::size_of::<*const u8>()), 8);
    let result42 = T::invoke(result41);
    let ptr43 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result42 {
        Ok(e) => {
            *ptr43.add(0).cast::<u8>() = (0i32) as u8;
            use ferrosa::udf::types::CqlValue as V54;
            match e {
                V54::Null => {
                    *ptr43.add(8).cast::<u8>() = (0i32) as u8;
                }
                V54::IntVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (1i32) as u8;
                    *ptr43.add(16).cast::<i32>() = _rt::as_i32(e);
                }
                V54::BigintVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (2i32) as u8;
                    *ptr43.add(16).cast::<i64>() = _rt::as_i64(e);
                }
                V54::FloatVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (3i32) as u8;
                    *ptr43.add(16).cast::<f32>() = _rt::as_f32(e);
                }
                V54::DoubleVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (4i32) as u8;
                    *ptr43.add(16).cast::<f64>() = _rt::as_f64(e);
                }
                V54::BooleanVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (5i32) as u8;
                    *ptr43.add(16).cast::<u8>() = (match e {
                        true => 1,
                        false => 0,
                    }) as u8;
                }
                V54::TextVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (6i32) as u8;
                    let vec44 = (e.into_bytes()).into_boxed_slice();
                    let ptr44 = vec44.as_ptr().cast::<u8>();
                    let len44 = vec44.len();
                    ::core::mem::forget(vec44);
                    *ptr43
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len44;
                    *ptr43.add(16).cast::<*mut u8>() = ptr44.cast_mut();
                }
                V54::BlobVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (7i32) as u8;
                    let vec45 = (e).into_boxed_slice();
                    let ptr45 = vec45.as_ptr().cast::<u8>();
                    let len45 = vec45.len();
                    ::core::mem::forget(vec45);
                    *ptr43
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len45;
                    *ptr43.add(16).cast::<*mut u8>() = ptr45.cast_mut();
                }
                V54::UuidVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (8i32) as u8;
                    let vec46 = (e.into_bytes()).into_boxed_slice();
                    let ptr46 = vec46.as_ptr().cast::<u8>();
                    let len46 = vec46.len();
                    ::core::mem::forget(vec46);
                    *ptr43
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len46;
                    *ptr43.add(16).cast::<*mut u8>() = ptr46.cast_mut();
                }
                V54::TimestampVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (9i32) as u8;
                    *ptr43.add(16).cast::<i64>() = _rt::as_i64(e);
                }
                V54::DateVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (10i32) as u8;
                    *ptr43.add(16).cast::<i32>() = _rt::as_i32(e);
                }
                V54::TimeVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (11i32) as u8;
                    *ptr43.add(16).cast::<i64>() = _rt::as_i64(e);
                }
                V54::SmallintVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (12i32) as u8;
                    *ptr43.add(16).cast::<u16>() = (_rt::as_i32(e)) as u16;
                }
                V54::TinyintVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (13i32) as u8;
                    *ptr43.add(16).cast::<u8>() = (_rt::as_i32(e)) as u8;
                }
                V54::InetVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (14i32) as u8;
                    let vec47 = (e.into_bytes()).into_boxed_slice();
                    let ptr47 = vec47.as_ptr().cast::<u8>();
                    let len47 = vec47.len();
                    ::core::mem::forget(vec47);
                    *ptr43
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len47;
                    *ptr43.add(16).cast::<*mut u8>() = ptr47.cast_mut();
                }
                V54::DecimalVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (15i32) as u8;
                    let (t48_0, t48_1) = e;
                    let vec49 = (t48_0).into_boxed_slice();
                    let ptr49 = vec49.as_ptr().cast::<u8>();
                    let len49 = vec49.len();
                    ::core::mem::forget(vec49);
                    *ptr43
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len49;
                    *ptr43.add(16).cast::<*mut u8>() = ptr49.cast_mut();
                    *ptr43
                        .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<i32>() = _rt::as_i32(t48_1);
                }
                V54::VarintVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (16i32) as u8;
                    let vec50 = (e).into_boxed_slice();
                    let ptr50 = vec50.as_ptr().cast::<u8>();
                    let len50 = vec50.len();
                    ::core::mem::forget(vec50);
                    *ptr43
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len50;
                    *ptr43.add(16).cast::<*mut u8>() = ptr50.cast_mut();
                }
                V54::DurationVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (17i32) as u8;
                    let (t51_0, t51_1, t51_2) = e;
                    *ptr43.add(16).cast::<i32>() = _rt::as_i32(t51_0);
                    *ptr43.add(20).cast::<i32>() = _rt::as_i32(t51_1);
                    *ptr43.add(24).cast::<i64>() = _rt::as_i64(t51_2);
                }
                V54::AsciiVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (18i32) as u8;
                    let vec52 = (e.into_bytes()).into_boxed_slice();
                    let ptr52 = vec52.as_ptr().cast::<u8>();
                    let len52 = vec52.len();
                    ::core::mem::forget(vec52);
                    *ptr43
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len52;
                    *ptr43.add(16).cast::<*mut u8>() = ptr52.cast_mut();
                }
                V54::TimeuuidVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (19i32) as u8;
                    let vec53 = (e.into_bytes()).into_boxed_slice();
                    let ptr53 = vec53.as_ptr().cast::<u8>();
                    let len53 = vec53.len();
                    ::core::mem::forget(vec53);
                    *ptr43
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len53;
                    *ptr43.add(16).cast::<*mut u8>() = ptr53.cast_mut();
                }
                V54::CounterVal(e) => {
                    *ptr43.add(8).cast::<u8>() = (20i32) as u8;
                    *ptr43.add(16).cast::<i64>() = _rt::as_i64(e);
                }
                V54::Unsupported => {
                    *ptr43.add(8).cast::<u8>() = (21i32) as u8;
                }
            }
        }
        Err(e) => {
            *ptr43.add(0).cast::<u8>() = (1i32) as u8;
            let vec55 = (e.into_bytes()).into_boxed_slice();
            let ptr55 = vec55.as_ptr().cast::<u8>();
            let len55 = vec55.len();
            ::core::mem::forget(vec55);
            *ptr43.add(8 + 1 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len55;
            *ptr43.add(8).cast::<*mut u8>() = ptr55.cast_mut();
        }
    };
    ptr43
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_invoke<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = i32::from(*arg0.add(8).cast::<u8>());
            match l1 {
                0 => {}
                1 => {}
                2 => {}
                3 => {}
                4 => {}
                5 => {}
                6 => {
                    let l2 = *arg0.add(16).cast::<*mut u8>();
                    let l3 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                }
                7 => {
                    let l4 = *arg0.add(16).cast::<*mut u8>();
                    let l5 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base6 = l4;
                    let len6 = l5;
                    _rt::cabi_dealloc(base6, len6 * 1, 1);
                }
                8 => {
                    let l7 = *arg0.add(16).cast::<*mut u8>();
                    let l8 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l7, l8, 1);
                }
                9 => {}
                10 => {}
                11 => {}
                12 => {}
                13 => {}
                14 => {
                    let l9 = *arg0.add(16).cast::<*mut u8>();
                    let l10 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l9, l10, 1);
                }
                15 => {
                    let l11 = *arg0.add(16).cast::<*mut u8>();
                    let l12 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base13 = l11;
                    let len13 = l12;
                    _rt::cabi_dealloc(base13, len13 * 1, 1);
                }
                16 => {
                    let l14 = *arg0.add(16).cast::<*mut u8>();
                    let l15 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base16 = l14;
                    let len16 = l15;
                    _rt::cabi_dealloc(base16, len16 * 1, 1);
                }
                17 => {}
                18 => {
                    let l17 = *arg0.add(16).cast::<*mut u8>();
                    let l18 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l17, l18, 1);
                }
                19 => {
                    let l19 = *arg0.add(16).cast::<*mut u8>();
                    let l20 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l19, l20, 1);
                }
                20 => {}
                _ => {}
            }
        }
        _ => {
            let l21 = *arg0.add(8).cast::<*mut u8>();
            let l22 = *arg0
                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l21, l22, 1);
        }
    }
}
pub trait Guest {
    /// Entry point called by the Ferrosa UDF executor.
    ///
    /// `args` contains the function arguments in declaration order.
    /// Return `ok(cql-value::null)` to return SQL NULL.
    /// Return `err(string)` to signal a runtime error.
    fn invoke(args: _rt::Vec<CqlValue>) -> Result<CqlValue, _rt::String>;
}
#[doc(hidden)]
macro_rules! __export_world_udf_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "invoke")] unsafe extern "C" fn
        export_invoke(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_invoke_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_invoke")] unsafe extern "C" fn _post_return_invoke(arg0
        : * mut u8,) { unsafe { $($path_to_types)*:: __post_return_invoke::<$ty > (arg0)
        } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_udf_cabi;
#[repr(align(8))]
struct _RetArea(
    [::core::mem::MaybeUninit<u8>; 24 + 2 * ::core::mem::size_of::<*const u8>()],
);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 24 + 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod ferrosa {
    pub mod udf {
        /// Simplified scalar-only CQL value type for guest UDFs.
        ///
        /// The canonical `ferrosa-udf.wit` defines the full `cql-value` variant
        /// including recursive collection types (list-val, set-val, map-val, etc.).
        /// The WebAssembly Component Model type system does not support recursive
        /// variant types via code-generation (wit-bindgen reports "type depends on
        /// itself").  The host works around this using the dynamic `Val` API.
        ///
        /// For scalar UDFs -- which operate only on primitive CQL types -- this
        /// simplified variant is equivalent: all scalar cases are identical, and the
        /// collection cases are replaced by a single `unsupported` catch-all that the
        /// host never sends to a scalar function.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub enum CqlValue {
                /// SQL-style NULL.
                Null,
                /// CQL int (32-bit signed).
                IntVal(i32),
                /// CQL bigint (64-bit signed).
                BigintVal(i64),
                /// CQL float (32-bit IEEE 754).
                FloatVal(f32),
                /// CQL double (64-bit IEEE 754).
                DoubleVal(f64),
                /// CQL boolean.
                BooleanVal(bool),
                /// CQL text / varchar.
                TextVal(_rt::String),
                /// CQL blob.
                BlobVal(_rt::Vec<u8>),
                /// CQL uuid / timeuuid (string-encoded).
                UuidVal(_rt::String),
                /// CQL timestamp (milliseconds since epoch).
                TimestampVal(i64),
                /// CQL date (days since epoch, signed).
                DateVal(i32),
                /// CQL time (nanoseconds since midnight).
                TimeVal(i64),
                /// CQL smallint (16-bit signed).
                SmallintVal(i16),
                /// CQL tinyint (8-bit signed).
                TinyintVal(i8),
                /// CQL inet address (dotted-decimal or IPv6 string).
                InetVal(_rt::String),
                /// CQL decimal (unscaled big-endian bytes, scale).
                DecimalVal((_rt::Vec<u8>, i32)),
                /// CQL varint (big-endian signed bytes).
                VarintVal(_rt::Vec<u8>),
                /// CQL duration (months, days, nanoseconds).
                DurationVal((i32, i32, i64)),
                /// CQL ascii.
                AsciiVal(_rt::String),
                /// CQL timeuuid (string-encoded).
                TimeuuidVal(_rt::String),
                /// CQL counter (64-bit signed).
                CounterVal(i64),
                /// Collection types (list/set/map/tuple/udt) are not supported for
                /// scalar UDFs.  The host will never pass a collection to a scalar
                /// function; this case exists only to keep the variant exhaustively
                /// matchable in implementations that use a wildcard arm.
                Unsupported,
            }
            impl ::core::fmt::Debug for CqlValue {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        CqlValue::Null => f.debug_tuple("CqlValue::Null").finish(),
                        CqlValue::IntVal(e) => {
                            f.debug_tuple("CqlValue::IntVal").field(e).finish()
                        }
                        CqlValue::BigintVal(e) => {
                            f.debug_tuple("CqlValue::BigintVal").field(e).finish()
                        }
                        CqlValue::FloatVal(e) => {
                            f.debug_tuple("CqlValue::FloatVal").field(e).finish()
                        }
                        CqlValue::DoubleVal(e) => {
                            f.debug_tuple("CqlValue::DoubleVal").field(e).finish()
                        }
                        CqlValue::BooleanVal(e) => {
                            f.debug_tuple("CqlValue::BooleanVal").field(e).finish()
                        }
                        CqlValue::TextVal(e) => {
                            f.debug_tuple("CqlValue::TextVal").field(e).finish()
                        }
                        CqlValue::BlobVal(e) => {
                            f.debug_tuple("CqlValue::BlobVal").field(e).finish()
                        }
                        CqlValue::UuidVal(e) => {
                            f.debug_tuple("CqlValue::UuidVal").field(e).finish()
                        }
                        CqlValue::TimestampVal(e) => {
                            f.debug_tuple("CqlValue::TimestampVal").field(e).finish()
                        }
                        CqlValue::DateVal(e) => {
                            f.debug_tuple("CqlValue::DateVal").field(e).finish()
                        }
                        CqlValue::TimeVal(e) => {
                            f.debug_tuple("CqlValue::TimeVal").field(e).finish()
                        }
                        CqlValue::SmallintVal(e) => {
                            f.debug_tuple("CqlValue::SmallintVal").field(e).finish()
                        }
                        CqlValue::TinyintVal(e) => {
                            f.debug_tuple("CqlValue::TinyintVal").field(e).finish()
                        }
                        CqlValue::InetVal(e) => {
                            f.debug_tuple("CqlValue::InetVal").field(e).finish()
                        }
                        CqlValue::DecimalVal(e) => {
                            f.debug_tuple("CqlValue::DecimalVal").field(e).finish()
                        }
                        CqlValue::VarintVal(e) => {
                            f.debug_tuple("CqlValue::VarintVal").field(e).finish()
                        }
                        CqlValue::DurationVal(e) => {
                            f.debug_tuple("CqlValue::DurationVal").field(e).finish()
                        }
                        CqlValue::AsciiVal(e) => {
                            f.debug_tuple("CqlValue::AsciiVal").field(e).finish()
                        }
                        CqlValue::TimeuuidVal(e) => {
                            f.debug_tuple("CqlValue::TimeuuidVal").field(e).finish()
                        }
                        CqlValue::CounterVal(e) => {
                            f.debug_tuple("CqlValue::CounterVal").field(e).finish()
                        }
                        CqlValue::Unsupported => {
                            f.debug_tuple("CqlValue::Unsupported").finish()
                        }
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_f32<T: AsF32>(t: T) -> f32 {
        t.as_f32()
    }
    pub trait AsF32 {
        fn as_f32(self) -> f32;
    }
    impl<'a, T: Copy + AsF32> AsF32 for &'a T {
        fn as_f32(self) -> f32 {
            (*self).as_f32()
        }
    }
    impl AsF32 for f32 {
        #[inline]
        fn as_f32(self) -> f32 {
            self as f32
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_udf_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_udf_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_udf_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:ferrosa:udf@0.1.0:udf:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 574] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc4\x03\x01A\x02\x01\
A\x08\x01B\x05\x01p}\x01o\x02\0z\x01o\x03zzx\x01q\x16\x04null\0\0\x07int-val\x01\
z\0\x0abigint-val\x01x\0\x09float-val\x01v\0\x0adouble-val\x01u\0\x0bboolean-val\
\x01\x7f\0\x08text-val\x01s\0\x08blob-val\x01\0\0\x08uuid-val\x01s\0\x0dtimestam\
p-val\x01x\0\x08date-val\x01z\0\x08time-val\x01x\0\x0csmallint-val\x01|\0\x0btin\
yint-val\x01~\0\x08inet-val\x01s\0\x0bdecimal-val\x01\x01\0\x0avarint-val\x01\0\0\
\x0cduration-val\x01\x02\0\x09ascii-val\x01s\0\x0ctimeuuid-val\x01s\0\x0bcounter\
-val\x01x\0\x0bunsupported\0\0\x04\0\x09cql-value\x03\0\x03\x03\0\x17ferrosa:udf\
/types@0.1.0\x05\0\x02\x03\0\0\x09cql-value\x03\0\x09cql-value\x03\0\x01\x01p\x02\
\x01j\x01\x02\x01s\x01@\x01\x04args\x03\0\x04\x04\0\x06invoke\x01\x05\x04\0\x15f\
errosa:udf/udf@0.1.0\x04\0\x0b\x09\x01\0\x03udf\x03\0\0\0G\x09producers\x01\x0cp\
rocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
