#!/usr/bin/env python3
"""Generate real text embeddings for the threat-hunting example.

Reads ``corpus.json`` (indicators + actors + infrastructure edges + activity
counts + query strings), embeds every indicator description and every query
string with a local Ollama ``nomic-embed-text-v2-moe`` model (768-dim), and
writes runnable, self-contained CQL with the real vectors baked in:

  * ``../data.cql``     -- INSERTs for every table; indicator rows carry embeddings
  * ``../queries.cql``  -- the demo queries, ANN clauses filled with query vectors

No API key / network service is needed at query time. Re-run only when the
corpus changes:

  ollama pull nomic-embed-text-v2-moe
  python3 gen_embeddings.py

Override endpoint/model with OLLAMA_URL / OLLAMA_MODEL env vars.
"""

import json
import os
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434/api/embed")
MODEL = os.environ.get("OLLAMA_MODEL", "nomic-embed-text-v2-moe")
DIM = 768


def embed(text: str) -> list[float]:
    body = json.dumps({"model": MODEL, "input": text}).encode()
    req = urllib.request.Request(
        OLLAMA_URL, data=body, headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.load(resp)
    except Exception as e:  # noqa: BLE001 - surface the real cause
        sys.exit(
            f"embedding request to {OLLAMA_URL} (model {MODEL}) failed: {e}\n"
            f"Is Ollama running and the model pulled? `ollama pull {MODEL}`"
        )
    vec = data.get("embeddings", [data.get("embedding")])[0]
    if vec is None or len(vec) != DIM:
        sys.exit(f"expected {DIM}-dim embedding, got {None if vec is None else len(vec)}")
    return vec


def vec_literal(vec: list[float]) -> str:
    return "[" + ", ".join(f"{x:.6f}" for x in vec) + "]"


def cql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    corpus = json.loads((HERE / "corpus.json").read_text())
    out = ["-- GENERATED by embeddings/gen_embeddings.py -- do not edit by hand.",
           f"-- Embeddings: {MODEL} ({DIM}-dim), from each indicator description.",
           "USE threat;\n"]

    for a in corpus["actors"]:
        out.append(
            f"INSERT INTO actor (actor_id, name, origin) VALUES "
            f"({a['id']}, {cql_str(a['name'])}, {cql_str(a['origin'])});"
        )
    out.append("")

    for i in corpus["indicators"]:
        vec = embed(i["description"])
        print(f"  embedded indicator {i['id']}: {i['value'][:40]}", file=sys.stderr)
        out.append(
            f"INSERT INTO indicator (indicator_id, value, kind, description, embedding) VALUES "
            f"({i['id']}, {cql_str(i['value'])}, {cql_str(i['kind'])}, "
            f"{cql_str(i['description'])}, {vec_literal(vec)});"
        )
    out.append("")

    for (ind, act) in corpus["attributed"]:
        out.append(
            f"INSERT INTO attributed_to (indicator_id, actor_id) VALUES ({ind}, {act});"
        )
    out.append("")

    for (src, dst) in corpus["communicates"]:
        out.append(
            f"INSERT INTO communicates_with (src_indicator_id, dst_indicator_id) VALUES ({src}, {dst});"
        )
    out.append("")

    for c in corpus["activity_counts"]:
        out.append(
            f"INSERT INTO indicator_activity (indicator_id, minute, hits) VALUES "
            f"({c['indicator_id']}, {cql_str(c['minute'])}, {c['hits']});"
        )
    out.append("")
    (HERE.parent / "data.cql").write_text("\n".join(out) + "\n")
    print(f"wrote {HERE.parent / 'data.cql'} ({len(corpus['indicators'])} indicators)", file=sys.stderr)

    template = (HERE / "queries.template.cql").read_text()
    for q in corpus["queries"]:
        template = template.replace(f"@@Q:{q['name']}@@", vec_literal(embed(q["text"])))
        print(f"  embedded query {q['name']}", file=sys.stderr)
    if "@@Q:" in template:
        sys.exit("unfilled @@Q:...@@ placeholder remains in queries.template.cql")
    (HERE.parent / "queries.cql").write_text(template)
    print(f"wrote {HERE.parent / 'queries.cql'}", file=sys.stderr)


if __name__ == "__main__":
    main()
