// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type CqlValue = ferrosa::udf::types::CqlValue;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_init_cabi<T: Guest>(
    arg0: i32,
    arg1: i32,
    arg2: ::core::mem::MaybeUninit<u64>,
    arg3: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result6 = T::init(
        match arg0 {
            0 => None,
            1 => {
                let e = {
                    use ferrosa::udf::types::CqlValue as V5;
                    let v5 = match arg1 {
                        0 => V5::Null,
                        1 => {
                            let e5 = arg2.assume_init() as i64 as i32;
                            V5::IntVal(e5)
                        }
                        2 => {
                            let e5 = arg2.assume_init() as i64;
                            V5::BigintVal(e5)
                        }
                        3 => {
                            let e5 = f32::from_bits(arg2.assume_init() as i64 as u32);
                            V5::FloatVal(e5)
                        }
                        4 => {
                            let e5 = f64::from_bits(arg2.assume_init() as i64 as u64);
                            V5::DoubleVal(e5)
                        }
                        5 => {
                            let e5 = _rt::bool_lift(
                                arg2.assume_init() as i64 as i32 as u8,
                            );
                            V5::BooleanVal(e5)
                        }
                        6 => {
                            let e5 = {
                                let len0 = arg3;
                                let bytes0 = _rt::Vec::from_raw_parts(
                                    arg2.as_ptr().cast::<*mut u8>().read().cast(),
                                    len0,
                                    len0,
                                );
                                _rt::string_lift(bytes0)
                            };
                            V5::TextVal(e5)
                        }
                        7 => {
                            let e5 = {
                                let len1 = arg3;
                                _rt::Vec::from_raw_parts(
                                    arg2.as_ptr().cast::<*mut u8>().read().cast(),
                                    len1,
                                    len1,
                                )
                            };
                            V5::BlobVal(e5)
                        }
                        8 => {
                            let e5 = {
                                let len2 = arg3;
                                let bytes2 = _rt::Vec::from_raw_parts(
                                    arg2.as_ptr().cast::<*mut u8>().read().cast(),
                                    len2,
                                    len2,
                                );
                                _rt::string_lift(bytes2)
                            };
                            V5::UuidVal(e5)
                        }
                        9 => {
                            let e5 = arg2.assume_init() as i64;
                            V5::TimestampVal(e5)
                        }
                        10 => {
                            let e5 = arg2.assume_init() as i64 as i32;
                            V5::DateVal(e5)
                        }
                        11 => {
                            let e5 = arg2.assume_init() as i64;
                            V5::TimeVal(e5)
                        }
                        12 => {
                            let e5 = arg2.assume_init() as i64 as i32 as i16;
                            V5::SmallintVal(e5)
                        }
                        13 => {
                            let e5 = arg2.assume_init() as i64 as i32 as i8;
                            V5::TinyintVal(e5)
                        }
                        14 => {
                            let e5 = {
                                let len3 = arg3;
                                let bytes3 = _rt::Vec::from_raw_parts(
                                    arg2.as_ptr().cast::<*mut u8>().read().cast(),
                                    len3,
                                    len3,
                                );
                                _rt::string_lift(bytes3)
                            };
                            V5::InetVal(e5)
                        }
                        n => {
                            debug_assert_eq!(n, 15, "invalid enum discriminant");
                            let e5 = {
                                let len4 = arg3;
                                _rt::Vec::from_raw_parts(
                                    arg2.as_ptr().cast::<*mut u8>().read().cast(),
                                    len4,
                                    len4,
                                )
                            };
                            V5::CollectionVal(e5)
                        }
                    };
                    v5
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        },
    );
    let ptr7 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result6 {
        Ok(_) => {
            *ptr7.add(0).cast::<u8>() = (0i32) as u8;
        }
        Err(e) => {
            *ptr7.add(0).cast::<u8>() = (1i32) as u8;
            let vec8 = (e.into_bytes()).into_boxed_slice();
            let ptr8 = vec8.as_ptr().cast::<u8>();
            let len8 = vec8.len();
            ::core::mem::forget(vec8);
            *ptr7.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
            *ptr7.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr8
                .cast_mut();
        }
    };
    ptr7
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_init<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_accumulate_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let base27 = arg0;
    let len27 = arg1;
    let mut result27 = _rt::Vec::with_capacity(len27);
    for i in 0..len27 {
        let base = base27.add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
        let e27 = {
            let l0 = i32::from(*base.add(0).cast::<u8>());
            use ferrosa::udf::types::CqlValue as V26;
            let v26 = match l0 {
                0 => V26::Null,
                1 => {
                    let e26 = {
                        let l1 = *base.add(8).cast::<i32>();
                        l1
                    };
                    V26::IntVal(e26)
                }
                2 => {
                    let e26 = {
                        let l2 = *base.add(8).cast::<i64>();
                        l2
                    };
                    V26::BigintVal(e26)
                }
                3 => {
                    let e26 = {
                        let l3 = *base.add(8).cast::<f32>();
                        l3
                    };
                    V26::FloatVal(e26)
                }
                4 => {
                    let e26 = {
                        let l4 = *base.add(8).cast::<f64>();
                        l4
                    };
                    V26::DoubleVal(e26)
                }
                5 => {
                    let e26 = {
                        let l5 = i32::from(*base.add(8).cast::<u8>());
                        _rt::bool_lift(l5 as u8)
                    };
                    V26::BooleanVal(e26)
                }
                6 => {
                    let e26 = {
                        let l6 = *base.add(8).cast::<*mut u8>();
                        let l7 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len8 = l7;
                        let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                        _rt::string_lift(bytes8)
                    };
                    V26::TextVal(e26)
                }
                7 => {
                    let e26 = {
                        let l9 = *base.add(8).cast::<*mut u8>();
                        let l10 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len11 = l10;
                        _rt::Vec::from_raw_parts(l9.cast(), len11, len11)
                    };
                    V26::BlobVal(e26)
                }
                8 => {
                    let e26 = {
                        let l12 = *base.add(8).cast::<*mut u8>();
                        let l13 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len14 = l13;
                        let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);
                        _rt::string_lift(bytes14)
                    };
                    V26::UuidVal(e26)
                }
                9 => {
                    let e26 = {
                        let l15 = *base.add(8).cast::<i64>();
                        l15
                    };
                    V26::TimestampVal(e26)
                }
                10 => {
                    let e26 = {
                        let l16 = *base.add(8).cast::<i32>();
                        l16
                    };
                    V26::DateVal(e26)
                }
                11 => {
                    let e26 = {
                        let l17 = *base.add(8).cast::<i64>();
                        l17
                    };
                    V26::TimeVal(e26)
                }
                12 => {
                    let e26 = {
                        let l18 = i32::from(*base.add(8).cast::<i16>());
                        l18 as i16
                    };
                    V26::SmallintVal(e26)
                }
                13 => {
                    let e26 = {
                        let l19 = i32::from(*base.add(8).cast::<i8>());
                        l19 as i8
                    };
                    V26::TinyintVal(e26)
                }
                14 => {
                    let e26 = {
                        let l20 = *base.add(8).cast::<*mut u8>();
                        let l21 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len22 = l21;
                        let bytes22 = _rt::Vec::from_raw_parts(l20.cast(), len22, len22);
                        _rt::string_lift(bytes22)
                    };
                    V26::InetVal(e26)
                }
                n => {
                    debug_assert_eq!(n, 15, "invalid enum discriminant");
                    let e26 = {
                        let l23 = *base.add(8).cast::<*mut u8>();
                        let l24 = *base
                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len25 = l24;
                        _rt::Vec::from_raw_parts(l23.cast(), len25, len25)
                    };
                    V26::CollectionVal(e26)
                }
            };
            v26
        };
        result27.push(e27);
    }
    _rt::cabi_dealloc(base27, len27 * (8 + 2 * ::core::mem::size_of::<*const u8>()), 8);
    let result28 = T::accumulate(result27);
    let ptr29 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result28 {
        Ok(_) => {
            *ptr29.add(0).cast::<u8>() = (0i32) as u8;
        }
        Err(e) => {
            *ptr29.add(0).cast::<u8>() = (1i32) as u8;
            let vec30 = (e.into_bytes()).into_boxed_slice();
            let ptr30 = vec30.as_ptr().cast::<u8>();
            let len30 = vec30.len();
            ::core::mem::forget(vec30);
            *ptr29.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len30;
            *ptr29.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr30
                .cast_mut();
        }
    };
    ptr29
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_accumulate<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_merge_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let result1 = T::merge(_rt::Vec::from_raw_parts(arg0.cast(), len0, len0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
        Ok(_) => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
        }
        Err(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let vec3 = (e.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3
                .cast_mut();
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_merge<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_serialize_state_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::serialize_state();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec2 = (result0).into_boxed_slice();
    let ptr2 = vec2.as_ptr().cast::<u8>();
    let len2 = vec2.len();
    ::core::mem::forget(vec2);
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_serialize_state<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base2 = l0;
    let len2 = l1;
    _rt::cabi_dealloc(base2, len2 * 1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_finalize_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::finalize();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result0 {
        Ok(e) => {
            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
            use ferrosa::udf::types::CqlValue as V7;
            match e {
                V7::Null => {
                    *ptr1.add(8).cast::<u8>() = (0i32) as u8;
                }
                V7::IntVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (1i32) as u8;
                    *ptr1.add(16).cast::<i32>() = _rt::as_i32(e);
                }
                V7::BigintVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (2i32) as u8;
                    *ptr1.add(16).cast::<i64>() = _rt::as_i64(e);
                }
                V7::FloatVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (3i32) as u8;
                    *ptr1.add(16).cast::<f32>() = _rt::as_f32(e);
                }
                V7::DoubleVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (4i32) as u8;
                    *ptr1.add(16).cast::<f64>() = _rt::as_f64(e);
                }
                V7::BooleanVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (5i32) as u8;
                    *ptr1.add(16).cast::<u8>() = (match e {
                        true => 1,
                        false => 0,
                    }) as u8;
                }
                V7::TextVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (6i32) as u8;
                    let vec2 = (e.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len2;
                    *ptr1.add(16).cast::<*mut u8>() = ptr2.cast_mut();
                }
                V7::BlobVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (7i32) as u8;
                    let vec3 = (e).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len3;
                    *ptr1.add(16).cast::<*mut u8>() = ptr3.cast_mut();
                }
                V7::UuidVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (8i32) as u8;
                    let vec4 = (e.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr1
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len4;
                    *ptr1.add(16).cast::<*mut u8>() = ptr4.cast_mut();
                }
                V7::TimestampVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (9i32) as u8;
                    *ptr1.add(16).cast::<i64>() = _rt::as_i64(e);
                }
                V7::DateVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (10i32) as u8;
                    *ptr1.add(16).cast::<i32>() = _rt::as_i32(e);
                }
                V7::TimeVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (11i32) as u8;
                    *ptr1.add(16).cast::<i64>() = _rt::as_i64(e);
                }
                V7::SmallintVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (12i32) as u8;
                    *ptr1.add(16).cast::<u16>() = (_rt::as_i32(e)) as u16;
                }
                V7::TinyintVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (13i32) as u8;
                    *ptr1.add(16).cast::<u8>() = (_rt::as_i32(e)) as u8;
                }
                V7::InetVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (14i32) as u8;
                    let vec5 = (e.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr1
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len5;
                    *ptr1.add(16).cast::<*mut u8>() = ptr5.cast_mut();
                }
                V7::CollectionVal(e) => {
                    *ptr1.add(8).cast::<u8>() = (15i32) as u8;
                    let vec6 = (e).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *ptr1
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len6;
                    *ptr1.add(16).cast::<*mut u8>() = ptr6.cast_mut();
                }
            }
        }
        Err(e) => {
            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
            let vec8 = (e.into_bytes()).into_boxed_slice();
            let ptr8 = vec8.as_ptr().cast::<u8>();
            let len8 = vec8.len();
            ::core::mem::forget(vec8);
            *ptr1.add(8 + 1 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
            *ptr1.add(8).cast::<*mut u8>() = ptr8.cast_mut();
        }
    };
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_finalize<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = i32::from(*arg0.add(8).cast::<u8>());
            match l1 {
                0 => {}
                1 => {}
                2 => {}
                3 => {}
                4 => {}
                5 => {}
                6 => {
                    let l2 = *arg0.add(16).cast::<*mut u8>();
                    let l3 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                }
                7 => {
                    let l4 = *arg0.add(16).cast::<*mut u8>();
                    let l5 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base6 = l4;
                    let len6 = l5;
                    _rt::cabi_dealloc(base6, len6 * 1, 1);
                }
                8 => {
                    let l7 = *arg0.add(16).cast::<*mut u8>();
                    let l8 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l7, l8, 1);
                }
                9 => {}
                10 => {}
                11 => {}
                12 => {}
                13 => {}
                14 => {
                    let l9 = *arg0.add(16).cast::<*mut u8>();
                    let l10 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l9, l10, 1);
                }
                _ => {
                    let l11 = *arg0.add(16).cast::<*mut u8>();
                    let l12 = *arg0
                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base13 = l11;
                    let len13 = l12;
                    _rt::cabi_dealloc(base13, len13 * 1, 1);
                }
            }
        }
        _ => {
            let l14 = *arg0.add(8).cast::<*mut u8>();
            let l15 = *arg0
                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l14, l15, 1);
        }
    }
}
pub trait Guest {
    fn init(init_cond: Option<CqlValue>) -> Result<(), _rt::String>;
    fn accumulate(args: _rt::Vec<CqlValue>) -> Result<(), _rt::String>;
    fn merge(serialized_state: _rt::Vec<u8>) -> Result<(), _rt::String>;
    fn serialize_state() -> _rt::Vec<u8>;
    fn finalize() -> Result<CqlValue, _rt::String>;
}
#[doc(hidden)]
macro_rules! __export_world_uda_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "init")] unsafe extern "C" fn
        export_init(arg0 : i32, arg1 : i32, arg2 : ::core::mem::MaybeUninit::< u64 >,
        arg3 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_init_cabi::<$ty > (arg0, arg1, arg2, arg3) } } #[unsafe (export_name =
        "cabi_post_init")] unsafe extern "C" fn _post_return_init(arg0 : * mut u8,) {
        unsafe { $($path_to_types)*:: __post_return_init::<$ty > (arg0) } } #[unsafe
        (export_name = "accumulate")] unsafe extern "C" fn export_accumulate(arg0 : * mut
        u8, arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_accumulate_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "cabi_post_accumulate")] unsafe extern "C" fn _post_return_accumulate(arg0 : *
        mut u8,) { unsafe { $($path_to_types)*:: __post_return_accumulate::<$ty > (arg0)
        } } #[unsafe (export_name = "merge")] unsafe extern "C" fn export_merge(arg0 : *
        mut u8, arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_merge_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "cabi_post_merge")] unsafe extern "C" fn _post_return_merge(arg0 : * mut u8,) {
        unsafe { $($path_to_types)*:: __post_return_merge::<$ty > (arg0) } } #[unsafe
        (export_name = "serialize-state")] unsafe extern "C" fn export_serialize_state()
        -> * mut u8 { unsafe { $($path_to_types)*:: _export_serialize_state_cabi::<$ty >
        () } } #[unsafe (export_name = "cabi_post_serialize-state")] unsafe extern "C" fn
        _post_return_serialize_state(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_serialize_state::<$ty > (arg0) } } #[unsafe (export_name =
        "finalize")] unsafe extern "C" fn export_finalize() -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_finalize_cabi::<$ty > () } } #[unsafe (export_name =
        "cabi_post_finalize")] unsafe extern "C" fn _post_return_finalize(arg0 : * mut
        u8,) { unsafe { $($path_to_types)*:: __post_return_finalize::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_uda_cabi;
#[repr(align(8))]
struct _RetArea(
    [::core::mem::MaybeUninit<u8>; 16 + 2 * ::core::mem::size_of::<*const u8>()],
);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 16 + 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod ferrosa {
    pub mod udf {
        /// Simplified CQL value type for guest use. The recursive collection variants
        /// (list-val, set-val, map-val, tuple-val, udt-val) from the host WIT are
        /// represented here as opaque blob-val payloads; the host is responsible for
        /// serializing/deserializing nested structures across the component boundary.
        /// This avoids recursive type cycles that WIT's topological resolver rejects.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub enum CqlValue {
                Null,
                IntVal(i32),
                BigintVal(i64),
                FloatVal(f32),
                DoubleVal(f64),
                BooleanVal(bool),
                TextVal(_rt::String),
                BlobVal(_rt::Vec<u8>),
                UuidVal(_rt::String),
                TimestampVal(i64),
                DateVal(i32),
                TimeVal(i64),
                SmallintVal(i16),
                TinyintVal(i8),
                InetVal(_rt::String),
                /// Collection and composite types are passed as msgpack-encoded blobs
                /// across the component boundary to avoid recursive WIT type cycles.
                /// The host encodes and decodes these; guests receive blob-val for them.
                CollectionVal(_rt::Vec<u8>),
            }
            impl ::core::fmt::Debug for CqlValue {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        CqlValue::Null => f.debug_tuple("CqlValue::Null").finish(),
                        CqlValue::IntVal(e) => {
                            f.debug_tuple("CqlValue::IntVal").field(e).finish()
                        }
                        CqlValue::BigintVal(e) => {
                            f.debug_tuple("CqlValue::BigintVal").field(e).finish()
                        }
                        CqlValue::FloatVal(e) => {
                            f.debug_tuple("CqlValue::FloatVal").field(e).finish()
                        }
                        CqlValue::DoubleVal(e) => {
                            f.debug_tuple("CqlValue::DoubleVal").field(e).finish()
                        }
                        CqlValue::BooleanVal(e) => {
                            f.debug_tuple("CqlValue::BooleanVal").field(e).finish()
                        }
                        CqlValue::TextVal(e) => {
                            f.debug_tuple("CqlValue::TextVal").field(e).finish()
                        }
                        CqlValue::BlobVal(e) => {
                            f.debug_tuple("CqlValue::BlobVal").field(e).finish()
                        }
                        CqlValue::UuidVal(e) => {
                            f.debug_tuple("CqlValue::UuidVal").field(e).finish()
                        }
                        CqlValue::TimestampVal(e) => {
                            f.debug_tuple("CqlValue::TimestampVal").field(e).finish()
                        }
                        CqlValue::DateVal(e) => {
                            f.debug_tuple("CqlValue::DateVal").field(e).finish()
                        }
                        CqlValue::TimeVal(e) => {
                            f.debug_tuple("CqlValue::TimeVal").field(e).finish()
                        }
                        CqlValue::SmallintVal(e) => {
                            f.debug_tuple("CqlValue::SmallintVal").field(e).finish()
                        }
                        CqlValue::TinyintVal(e) => {
                            f.debug_tuple("CqlValue::TinyintVal").field(e).finish()
                        }
                        CqlValue::InetVal(e) => {
                            f.debug_tuple("CqlValue::InetVal").field(e).finish()
                        }
                        CqlValue::CollectionVal(e) => {
                            f.debug_tuple("CqlValue::CollectionVal").field(e).finish()
                        }
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_f32<T: AsF32>(t: T) -> f32 {
        t.as_f32()
    }
    pub trait AsF32 {
        fn as_f32(self) -> f32;
    }
    impl<'a, T: Copy + AsF32> AsF32 for &'a T {
        fn as_f32(self) -> f32 {
            (*self).as_f32()
        }
    }
    impl AsF32 for f32 {
        #[inline]
        fn as_f32(self) -> f32 {
            self as f32
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_uda_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_uda_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_uda_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:ferrosa:udf@0.1.0:uda:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 594] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd8\x03\x01A\x02\x01\
A\x13\x01B\x03\x01p}\x01q\x10\x04null\0\0\x07int-val\x01z\0\x0abigint-val\x01x\0\
\x09float-val\x01v\0\x0adouble-val\x01u\0\x0bboolean-val\x01\x7f\0\x08text-val\x01\
s\0\x08blob-val\x01\0\0\x08uuid-val\x01s\0\x0dtimestamp-val\x01x\0\x08date-val\x01\
z\0\x08time-val\x01x\0\x0csmallint-val\x01|\0\x0btinyint-val\x01~\0\x08inet-val\x01\
s\0\x0ecollection-val\x01\0\0\x04\0\x09cql-value\x03\0\x01\x03\0\x17ferrosa:udf/\
types@0.1.0\x05\0\x02\x03\0\0\x09cql-value\x03\0\x09cql-value\x03\0\x01\x01k\x02\
\x01j\0\x01s\x01@\x01\x09init-cond\x03\0\x04\x04\0\x04init\x01\x05\x01p\x02\x01@\
\x01\x04args\x06\0\x04\x04\0\x0aaccumulate\x01\x07\x01p}\x01@\x01\x10serialized-\
state\x08\0\x04\x04\0\x05merge\x01\x09\x01@\0\0\x08\x04\0\x0fserialize-state\x01\
\x0a\x01j\x01\x02\x01s\x01@\0\0\x0b\x04\0\x08finalize\x01\x0c\x04\0\x15ferrosa:u\
df/uda@0.1.0\x04\0\x0b\x09\x01\0\x03uda\x03\0\0\0G\x09producers\x01\x0cprocessed\
-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
